//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace MasterProjekat1.Model
{
    public class AnalitickiKonto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual Guid ID
        {
            get;
            set;
        }
        public virtual string Sifra
        {
            get;
            set;
        }

        public virtual string Naziv
        {
            get;
            set;
        }

        public List<Promena> Promene
        {
            get;
            set;
        }


        public Guid GlavnaKnjiga_ID { get; set; }

        [ForeignKey("GlavnaKnjiga_ID")]
        public virtual GlavnaKnjiga GlavnaKnjiga
        {
            get;
            set;
        }

    }
}
