//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace MasterProjekat1.Model
{
    public class NalogZaKnjizenje
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual Guid ID
        {
            get;
            set;
        }
        public virtual int BrojNaloga
        {
            get;
            set;
        }

       
        public virtual DateTime DatumNaloga
        {
            get;
            set;
        }

        public virtual Decimal DugujeUk
        {
            get;
            set;
        }


        public virtual int RedniBroj
        {
            get;
            set;
        }

        public virtual Decimal PotrazujeUk
        {
            get;
            set;
        }


        public virtual DateTime DatumKnjizenja
        {
            get;
            set;
        }

        public Guid PoslovnaGodina_ID { get; set; }

        [ForeignKey("PoslovnaGodina_ID")]

        public virtual PoslovnaGodina PoslovnaGodina
        {
            get;
            set;
        }

        public Guid VrstaNaloga_ID { get; set; }

        [ForeignKey("VrstaNaloga_ID")]
        public virtual VrstaNaloga VrstaNaloga
        {
            get;
            set;
        }

        public virtual List<Promena> Promene
        {
            get;
            set;
        }

    }
}
