//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace MasterProjekat1.Model
{
    public class PoslovniPartner
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual new Guid ID
        {
            get;
            set;
        }
        public  string Adresa
        {
            get;
            set;
        }

         public IEnumerable<Email> Emailovi
        {
            get;
            set;
        }

        public  string Naziv
        {
            get;
            set;
        }

        public  bool ObveznikPDV
        {
            get;
            set;
        }

        
        public  int PIB
        {
            get;
            set;
        }

        public IEnumerable<Racun> Racuni
        {
            get;
            set;
        }

         public string SifraDelatnosti
        {
            get;
            set;
        }

         public IEnumerable<Telefon> Telefoni
        {
            get;
            set;
        }

        public int MaticniBroj
        {
            get;
            set;
        }

        public Guid Preduzece_ID { get; set; }

        [ForeignKey("Preduzece_ID")]
        public virtual Preduzece preduzece
        {
            get;
            set;
        }

        public List<Promena> Promene
        {
            get;
            set;
        }

    }
}
