//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace MasterProjekat1.Model
{
    public class Preduzece
    {
        public Preduzece()
        {
            Radnici = new List<Radnik>();
            PoslovniPartneri = new List<PoslovniPartner>();
            OrganizacioneJedinice = new List<OrganizacionaJedinica>();
            Emailovi = new List<Email>();
            Telefoni = new List<Telefon>();
            Racuni = new List<Racun>();  
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual Guid ID
        {
            get;
            set;
        }
        public virtual string Naziv
        {
            get;
            set;
        }

        public virtual string Adresa
        {
            get;
            set;
        }

        public virtual int BrojNaloga
        {
            get;
            set;
        }

        public virtual int PIB
        {
            get;
            set;
        }
        public virtual int MaticniBroj
        {
            get;
            set;
        }

        public virtual bool ObveznikPDV
        {
            get;
            set;
        }

        public virtual string SifraDelatnosti
        {
            get;
            set;
        }

        public virtual IEnumerable<Radnik> Radnici
        {
            get;
            set;
        }

        public virtual IEnumerable<PoslovniPartner> PoslovniPartneri
        {
            get;
            set;
        }

        public virtual IEnumerable<OrganizacionaJedinica> OrganizacioneJedinice
        {
            get;
            set;
        }

        public virtual IEnumerable<Email> Emailovi
        {
            get;
            set;
        }

        public virtual IEnumerable<Telefon> Telefoni
        {
            get;
            set;
        }

        public virtual IEnumerable<Racun> Racuni
        {
            get;
            set;
        }

    }
}

