//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace MasterProjekat1.Model
{
    public class Radnik
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual Guid ID
        {
            get;
            set;
        }
        public virtual string Ime
        {
            get;
            set;
        }

        public virtual string Prezime
        {
            get;
            set;
        }

        
        public virtual int JMBG
        {
            get;
            set;
        }

        public virtual string StrucnaSprema
        {
            get;
            set;
        }

        public virtual string SifraRadnika
        {
            get;
            set;
        }

        public virtual DateTime DatumZaposlenja
        {
            get;
            set;
        }

        public virtual int BrojRadnihSati
        {
            get;
            set;
        }

        public virtual int BrojBodova
        {
            get;
            set;
        }
        public Guid Preduzece_ID { get; set; }

        [ForeignKey("Preduzece_ID")]
        public virtual Preduzece Preduzece
        {
            get;
            set;
        }

        public List<Promena> Promene
        {
            get;
            set;
        }

    }
}
